cognizant-ai-labs/covid-xprize

README.md

Rendered version [here](https://github.com/leaf-ai/covid-xprize/blob/add-links/README.md).

Include links to whitepaper and dashboard in README

---

.gitignore
examples/lstm/tests/test_xprize_predictor.py

The test was assuming the data file was present. It now downloads it if needed.

#81 Fix test_xprize_predictor by downloading the raw data if needed

---

codefresh.yml
examples/predictors/lstm/xprize_predictor.py
validation/scenario_generator.py
validation/tests/test_validation.py

I verified that Codefresh detects an intentional test failure that I injected, and that it runs all tests, of which there are 25.
I also cleaned up the logging noise so it's easier to see what's actually going on with the tests.

Clean up warnings to make it easier to see actual issues

---

Predictor_submission_template.ipynb
examples/predictors/linear/Example-Train-Linear-Rollout-Model.ipynb
examples/predictors/lstm/Example-LSTM-Predictor.ipynb
examples/predictors/lstm/data/uk_populations.csv
examples/predictors/lstm/xprize_predictor.py

- Properly handle country and regions using a dedicated, unique GeoID column
- Predict for ALL geos passed in IP file: returning 0 for geos for which we don't have enough data
- Predict since last known date if needed, and return predictions for requested dates only

Make LSTM pass validation checks

---

covid_xprize/examples/prescriptors/random/prescribe.py
predictor_robojudge.ipynb
predictor_submission_template.ipynb
prescriptor_robojudge.ipynb

Ran the notebooks from a clean env and fixed a few things

Smoke check

---

resources.md

Added a page with useful links and papers. More to be added later.

#120 Add a Resources page with pointers to useful resources for competitors.

---

covid_xprize/examples/predictors/linear/Example-Train-Linear-Rollout-Model.ipynb

We are predicting T + 2 instead of T + 1 here where T is the last historically available data.

Fix bug in label creation code

---

covid_xprize/scoring/predictor_scoring.py
predictor_robojudge.ipynb

Updated `predictor_robjojudge` notebook to plot forecasts to make it easy to compare predictors against each other, as well as against ground truth.

#138 Plot predictors forecasts in predictor_robojudge.ipynb

---

countries_regions.csv

Added a list of all countries and regions that will be used to compute the MAE/100K.

#143 Provide the list of countries and regions used to compute predictors MAE

---

covid_xprize/scoring/predictor_scoring.py
predictor_robojudge.ipynb

Limit the number of countries and regions used in robojudge to countries_regions.csv
And some cleanup.

#145 Limit the number of countries and regions used in robojudge

---

covid_xprize/validation/scenario_generator.py

It's now possible to call scenario_generator from the command line

#152 Add a main function to scenario_generator.py to execute it from command line

---

covid_xprize/validation/predictor_validation.py
covid_xprize/validation/prescriptor_validation.py
covid_xprize/validation/tests/fixtures/predictor/string_daily_cases_submission.csv
covid_xprize/validation/tests/test_predictor_validation.py

Validating column PredictedDailyNewCases contains numbers

#154 Check column PredictedDailyNewCases contains numbers

---

covid_xprize/validation/predictor_validation.py
covid_xprize/validation/tests/fixtures/predictor/string_date_submission.csv
covid_xprize/validation/tests/test_predictor_validation.py

Check Pandas was indeed able to parse the `Date` column as dates.

#161 Check Date column contains dates

---

prescribe.py

Added a `prescribe.py` api to be implemented by teams.

#171 Provide a prescribe.py api

---

requirements.txt
setup.py

Added a few `__init__.py` to make `setup.py` consider these directories as modules.
Also fixed h5py to what tensorflow wants, and upgraded the patch version of tensorflow to get a small security patch.

#175 Make covid_xprize/examples/prescriptors a module

---

covid_xprize/validation/prescriptor_validation.py
covid_xprize/validation/tests/fixtures/prescriptor/string_date_submission.csv
covid_xprize/validation/tests/fixtures/prescriptor/string_npi_submission.csv
covid_xprize/validation/tests/test_prescriptor_validation.py

Checks generated prescriptions contain valid dates and NPI values and added a `main` method to run the script from command line.

Check NPI columns contain numerical values

---

countries_regions.csv
countries_regions_phase1_fix.csv
covid_xprize/validation/scenario_generator.ipynb
covid_xprize/validation/scenario_generator.py
setup.py

Removed country `United States Virgin Islands` from the list of countries and regions for Phase 2
Made `scenario_generator` backward compatible with Phase 1 by converting `United States Virgin Islands` into separate country and region.

Manage United States Virgin Islands

---

covid_xprize/validation/scenario_generator.ipynb

Added a new prescriptor's test task for China early 2020. This is the code generate its IPs file.

Add scenario to generate hitorical IPs for China early 2020's prescription task

---

covid_xprize/validation/cost_generator.py

Provide a way to specify a list of countries for which to generate costs

#200 Specify list of countries and regions for cost_generator

---

covid_xprize/scoring/predictor_scoring.py
setup.py

`load_dataset`'s filtering on nan regions was broken when specifying a list of countries and regions

#200 Fix filter on nan regions

---

covid_xprize/scoring/prescriptor_scoring.py
prescriptor_robojudge.ipynb

To handle the case when prescriptions start after predictor data set ends.

Prepend past ips to prescriptions

---

covid_xprize/examples/predictors/linear/Example-Train-Linear-Rollout-Model.ipynb
covid_xprize/examples/predictors/linear/predict.py
covid_xprize/examples/predictors/lstm/Example-LSTM-Predictor.ipynb
covid_xprize/examples/predictors/lstm/tests/test_xprize_predictor.py
covid_xprize/examples/predictors/lstm/xprize_predictor.py
covid_xprize/examples/prescriptors/blind_greedy/prescribe.py
covid_xprize/examples/prescriptors/neat/utils.py
covid_xprize/examples/prescriptors/random/prescribe.py
covid_xprize/examples/prescriptors/zero/prescribe.py
covid_xprize/scoring/predictor_scoring.py
covid_xprize/scoring/prescriptor_scoring.py
covid_xprize/standard_predictor/xprize_predictor.py
covid_xprize/validation/predictor_validation.py
covid_xprize/validation/prescriptor_validation.py
predictor_robojudge.ipynb
predictor_submission_template.ipynb

`error_bad_lines=False` gets replaced by `on_bad_lines='skip'`
`error_bad_lines=True` gets replaced by `on_bad_lines='error'`

Fix Pandas error_bad_lines deprecation warnings

---

Dockerfile
codefresh.yml
requirements.txt

Fix the Codefresh builds
Upgraded to Python 3.10 and ran the tests

Python 3.10

---

setup.py

I needed to include some extra data files in the setup.py configuration for the package.

Configure setup py

---

covid_xprize/validation/scenario_generator.py

Scenario generator should handle NaN values present in the raw dataframe it accepts as input

Minor change to scenario generator
